site_name: Social-Seq doc
nav:
  - Language English: 'https://lilab-cibr.github.io/Social_Seq/en/'
  - 语言 中文: 'https://lilab-cibr.github.io/Social_Seq/'
  - 首页: index.md
  - 文章图表复现: figure_reproduce.md
  - 设备组装和清单:
    - 硬件清单: 设备组装和清单/shopping_list.md
    - OBS软件安装: 设备组装和清单/OBS_软件安装.md
    - 服务器环境配置: 设备组装和清单/服务器环境配置.md

  - 基础使用培训:
    - 连接进入服务器: 基础使用培训/login_server.md
    - 一些基础技能: 基础使用培训/basic_command.md
    - 已安装的深度学习模型: 基础使用培训/installed_models.md

  - 小球矫正:
    - 代码流程: 小球矫正/process.md
    - 应用场景: 小球矫正/application.md
    - 数据集制作&模型更新: 小球矫正/dataset.md

  - 单鼠三维姿态计算:
    - 代码流程: 单鼠三维姿态重构/process.md
    - 应用场景: 单鼠三维姿态重构/application.md
    - 数据集制作&模型更新: 单鼠三维姿态重构/dataset.md

  - 社交三维姿态计算 (Social):
    - 代码流程: 社交三维姿态重构/process.md
    - 应用场景: 社交三维姿态重构/application.md
    - 数据集制作&模型更新: 社交三维姿态重构/dataset.md

  - 社交序列标签 (Seq):
    - 代码流程: 社交序列标签/process.md
    - 应用场景: 社交序列标签/application.md
    - 聚类和模板制作: 社交序列标签/dataset.md

  - 闭环行为控制 (Live):
    - 代码流程: 闭环行为控制/process.md
    - 应用场景: 闭环行为控制/application.md

theme:
  name: readthedocs
  collapse_navigation: true  # 允许折叠导航
  sticky_navigation: true   # 侧边栏在滚动时固定
  language_selector: true  # 显示语言选择器
  language: zh


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - css/custom.css

# 添加多语言插件配置
plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          nav_translations:
            首页: Home
            文章图表复现: Figure Reproduction
            设备组装和清单: Equipment Assembly & List
            硬件清单: Hardware List
            OBS软件安装: OBS Software Installation
            服务器环境配置: Server Environment Configuration
            基础使用培训: Basic Usage Training
            连接进入服务器: Login to Server
            一些基础技能: Basic Commands
            已安装的深度学习模型: Installed Deep Learning Models
            小球矫正: Ball Correction
            代码流程: Workflow
            应用场景: Applications
            数据集制作&模型更新: Dataset & Model Updates
            单鼠三维姿态计算: Single Mouse 3D Pose
            代码流程: Workflow
            应用场景: Applications
            数据集制作&模型更新: Dataset & Model Updates
            代码流程: Workflow
            应用场景: Applications
            数据集制作&模型更新: Dataset & Model Updates
            代码流程: Workflow
            应用场景: Applications
            聚类和模板制作: Clustering & Template Creation
            代码流程: Workflow
            应用场景: Applications
            社交三维姿态计算 (Social): Social 3D Pose (Social)
            社交序列标签 (Seq): Sequence Labeling (Seq)
            闭环行为控制 (Live): Closed-loop Control (Live)
        - locale: zh
          name: 中文
          build: true
          default: true
