site_name: Social-Seq doc
nav:
  - 首页: index.md
  - 关于: about.md
  - 设备组装和清单:
    - 硬件清单: 设备组装和清单/shopping_list.md
    - OBS软件安装: 设备组装和清单/OBS_软件安装.md
    
  - 基础使用培训:
    - 连接进入服务器: 基础使用培训/login_server.md
    - 一些基础技能: 基础使用培训/basic_command.md
    - 已安装的深度学习模型: 基础使用培训/installed_models.md

  - 小球矫正:
    - 代码流程: 小球矫正/process.md
    - 应用场景: 小球矫正/application.md
    - 数据集制作&模型更新: 小球矫正/dataset.md

  - 单鼠三维姿态计算:
    - 代码流程: 单鼠三维姿态重构/process.md
    - 应用场景: 单鼠三维姿态重构/application.md
    - 数据集制作&模型更新: 单鼠三维姿态重构/dataset.md

  - 社交三维姿态计算 (Social):
    - 代码流程: 社交三维姿态重构/process.md
    - 应用场景: 社交三维姿态重构/application.md
    - 数据集制作&模型更新: 社交三维姿态重构/dataset.md

  - 社交序列标签 (Seq):
    - 代码流程: 社交序列标签/process.md
    - 应用场景: 社交序列标签/application.md
    - 聚类和模板制作: 社交序列标签/dataset.md

theme:
  name: readthedocs
  collapse_navigation: true  # 允许折叠导航
  sticky_navigation: true   # 侧边栏在滚动时固定
  # navigation_depth: 4

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - css/custom.css